### ISSUE TITLE
Overmind: proper url for various tournaments

### ISSUE THREAD

**Issue by Moergil** [hackcraft-sk/swarm#4]
Current system doesn't allow to provide link for specific tournament. Every tournament should exists in its own subdomain, or address, with possibility to set default/main/actual tournament when accessing plain domain.

**Comment by nixone** [comment]
I did contact the company hosting our system, they are not sure if this is possible (linking generic *.mylifeforai.com to mylifeforai.com /rubbish/), so far the plan is to do it at least http://mylifeforai.com/scmai5 for example, so link can be forwarded to anybody
